# gmapping_params.yaml

# Map parameters
map_update_interval: 5.0      # 맵 업데이트 간격을 더 자주 하도록 5초로 설정
map_resolution: 0.1          # 더 촘촘한 맵을 위해 해상도를 0.03m (3cm)로 줄임

# GMapping parameters
delta: 0.05                   # 스캔 매칭의 각도 변화(촘촘한 맵을 위해 값 축소)
sigma: 0.02                   # 스캔 매칭의 표준 편차를 줄여 더 정확한 매칭
lstep: 0.02                   # 스캔 매칭 시 더 작은 스텝 크기로 이동
astep: 0.02                   # 스캔 매칭 시 더 작은 각도 스텝 크기로 설정
srr: 0.05                     # 더 작은 오도메트리 노이즈 값으로 설정
srt: 0.05                     # 오도메트리 회전에 대한 노이즈 값 축소
str: 0.05                     # 오도메트리에서 직선 이동과 회전 간의 노이즈 값 축소
stt: 0.05                     # 회전의 노이즈 값을 줄여 정확도를 높임

